### PR TITLE
Adds an XML to OBFL step using Dotify

### PR DESCRIPTION
**Pull request by joeha480**
The step to use in the XSLT path. I wanted to verify that it works etc, but I don't know how. I'd be happy to continue working on it, but I need some help.

### CODE REVIEW

**Comment by bertfrees** [comment]
Thanks Joel. Something else than I expected but equally fine. (I had expected an XProc step not implemented in Java that would use `p:xslt` to invoke the XSLT, which would have to be made available somehow through the Pipeline's resource resolution mechanism (XML Catalogs). Probably the reason you did it this way is so that you could reuse the `TaskSystem` logic you had already written?)

The changes look good. I will write a test and try to get it working.

**Comment by bertfrees** [comment]
Question: where does this block fit in your [Dotify + DP2 Braille Modules](https://docs.google.com/drawings/d/1lyiuwHZhACE5A5G2H29Ey42Iu0bzOrFlYTnwrKF3uSA) diagram? It is "Layout interpreter" right? And does it also include "Style selector" (version of 1 Sept)? If yes, and if we would like to move "Style selector" to the position of the diagram later, would this `dotify:xml-to-obfl` step still be usable?

**Comment by joeha480** [comment]
Yes, I called it the layout interpreter in the current version of the diagram. We'll probably have to make some adjustments, but I don't think we need to worry about that now. By the way, I haven't released the dotify.task.impl artifact yet, but it's in sonatype snapshots. I wanted to make sure the integration with Pipeline works before I release it.

**Comment by bertfrees** [comment]
merged in deb69b5

**Pull request closed without merging**
