### PR TITLE
Updates to dotify 3.0 releases

### PR DESCRIPTION
**Pull request by bertfrees**
This PR is part of https://github.com/daisy/pipeline/pull/498.

### CODE REVIEW

**Comment by bertfrees** [comment]
@joeha480 Do you have an idea why [test_obfl-to-pef.xprocspec](https://github.com/daisy/pipeline-mod-braille/blob/b50d7d70896333faf1d6a6afac391b33549e6d6e/pipeline-braille-utils/dotify-utils/dotify-calabash/src/test/xprocspec/test_obfl-to-pef.xprocspec) is now broken?

**Comment by bertfrees** [comment]
There is a warning:

> WARN  o.d.dotify.obfl.impl.ExpressionImpl - int2text operation is not supported in the current configuration.

**Comment by joeha480** [comment]
I'll have a look.

**Comment by joeha480** [comment]
There's an error in the dotify.formatter.impl:3.0.0 which prevents it from loading the reference to int2text in OSGi. I'll release v3.1.0 shortly and update the PR.

**Comment by bertfrees** [comment]
Thanks.

**Comment by joeha480** [comment]
I've updated the PR now, and it works for me, but I never saw the error you talked about. Does it show up if I run `make check` in the super project?

**Comment by bertfrees** [comment]
Thanks, it builds now. That warning showed up in the test.log file of the dotify-calabash module (under target). You don't see it when you run `make check`. You'll just see that the test fails.

**Pull request merged**
