### PR TITLE
Datatypes

### PR DESCRIPTION
**Pull request by josteinaj**
Datatypes for line spacing, contraction grade, and translator. Created by @usama49, modified and rebased by me, and not tested yet. Not implemented in the Web UI yet either, so we'll have to test more before merging anything.

### CODE REVIEW

**Comment by bertfrees** [comment]
Thanks Jostein. The datatypes are fine, especially the documentation elements I like. However I'm not so sure about the "transformer query" part. The way you have done things are different from the approach I had in mind.

The issue we are trying to solve here is the following: we have a bunch of options and we want to correctly handle invalid combinations and make it as easy as possible for the user to select a valid combination.

The main problem I have with your approach this is that it breaks extensibility, and a secondary problem is that you are adding control flow to XProc. What you are doing basically is validate and process combinations of options with XProc and static datatype files. However some options, such as contraction grade, are already validated and processed on the level of transformer providers, in an extensible way (meaning you can add your own transformer provider services). Doing it in XProc and static datatype files means you are cancelling this extensibility, and also you are adding control flow to XProc which is something I have been trying to move away from because I think that is not what XProc is meant for: as soon as things get more complex it gets clumsy and some things can't even be done at all. (See https://docs.google.com/document/d/1VsNUDPzrIsxsEM31Fb1dOU9NE-rp5tiuEHF1SBz2oMc/edit#heading=h.p2wsx9wcg6tt.) A possible additional problem is the "fuzzy matching", e.g. when German grade 3 is specified it would result in German grade 2 which is not what was requested. Maybe it would be better to throw a runtime error in this case.

We can avoid some XProc logic by simply passing options such as contraction grade etc. to the transformer providers by constructing a transform query without any special handling. The query will come back with an error if there was no match. If we want to keep the "transform" option too, but we don't wish to parse it in XProc in order to combine it with the other options, we could possibly do that in Java if we pass two queries (user-provided one and programmatically constructed one).

But this doesn't solve the main problem: how do we limit the number of invalid combinations of options if we can't hard-code anything in static datatype files?

We could dynamically compute datatypes, however this can only be done for individual options, not for combinations of options. So still not an ideal solution.

The solution I had in mind is to move some options to agency-specific scripts. Some options are clearly more generic and standalone than other, so they should definitely stay in a shared script, but if moving a few options to specific scripts can greatly simplify things I think we should do it. Hard-coding stuff in an agency-specific script is much more acceptable than in a generic script because it doesn't have such a big impact on the extensibility.

Regarding the datatype names ("line-spacing" vs. "braille-line-spacing"): I would even go further. I would rather have names that are specific to the script itself unless the types are defined in a shared component. So, if the type is defined in dtbook-to-pef, I would call it "dtbook-to-pef-line-spacing" or "dtbook-to-pef:line-spacing". This is also tge reason I would have liked the prefixes to have the meaning of an actual namespace: then the name could be shortened to "d:line-spacing" with `xmlns:d="http://www.daisy.org/pipeline/modules/braille/dtbook-to-pef/"`.

**Comment by josteinaj** [comment]
> I'm not so sure about the "transformer query" part.

Ok, no problem, let's change it. I was trying to add an override mechanism in case you wanted to specify some key:value pairs manually, but if it doesn't play well with other parts of the system then I don't mind changing it.

So I guess what the best solution here is depends a lot on whether or not we go for agency-specific scripts? I thought we wanted to try and have a common script if possible?

If we create agency-specific scripts, would we also have a generic non-agency-specific script exposed for those who want full access to all options?

> (...) I would call it "dtbook-to-pef-line-spacing" or "dtbook-to-pef:line-spacing" (...)

I like it. Let's use the script ID in the naming.

As for namespaces I'd like to avoid requiring the clients to be namespace aware, which means avoiding namespace prefixes. Clark notation could work I guess if you want namespaces, so that you don't have to pass stuff like `xmlns:dtbook-to-pef="..."` back and forth when communicating with the web api.

Yet another alternative might be to have the module name be part of the datatype URL in the web api, so for instance you could get `http://localhost:8181/ws/datatypes/dtbook-to-pef/line-spacing`, or maybe like `http://localhost:8181/ws/datatypes/org.daisy.pipeline.modules.braille/dtbook-to-pef/line-spacing`. That would of course require some changes to the web api, but it's an idea.

**Comment by bertfrees** [comment]
> So I guess what the best solution here is depends a lot on whether or not we go for agency-specific scripts? I thought we wanted to try and have a common script if possible?

Yes I know. We indeed said we want as much options as possible in common, and that goal still holds, but the "as possible" is important. We need to make some compromises in order to get a user-friendly interface. Most option are quite generic and we should at least have those in common, even if they will only be used by one agency, and we have agency-specific scripts. The idea is that the common options improve visibility between agencies.

> If we create agency-specific scripts, would we also have a generic non-agency-specific script exposed for those who want full access to all options?

Yes, I think that would be a very good idea, if it's possible. I guess this would mean that all functionality (or as much as possible) would be in the generic script, and the agency specific scripts would become nothing more than some kind of configuration files that forward (or possible hide some) options to the generic script, and redefine some datatypes to make the user interface more specific.

This is of course the ideal situation. I can imagine it may be tempting for agencies to implement new agency-specific behavior in their own script even when it is possible to add it to the generic one, because it's easier/faster. This you can try to avoid by making good agreements. However there are cases where implementing something in an agency-specific really adds value, for example because you could also have agency-specific documentation. I'm thinking for example about including a default stylesheet and adapting the script documentation to that stylesheet. Supporting these kind of things in a generic script is more challenging. A possible solution is to add this specific documentation to templates that use a specific stylesheet.

**Comment by bertfrees** [comment]
I just got an idea. Maybe it's far-fetched but I'd like to know what you think:

The `documentation` element with child `value` elements in `choice` types: I assume you will render these as items in the dropdown list. Wouldn't it be cool if you could somehow have more extensive documentation for option values which would also show up in the user interface, for example beneath the dropdown list when you have selected a value. The extended description could e.g. be specified as of the second line, just like we do with descriptions of options.

I'm specifically thinking about documenting CSS stylesheets that you can choose from a dropdown list.

**Comment by josteinaj** [comment]
Interesting, I like it.

If we change the dropdown to radio buttons we could even have those detailed descriptions showing all the time, and not only when you've selected the option. How do you think the XML should look? How about something like this?

```xml
<choice id="dtbook-to-pef:braille-translator">
    <value>celia</value>
    <value>dedicon</value>
    (...)
    
    <documentation xmlns="http://relaxng.org/ns/compatibility/annotations/1.0" xml:lang="en">
        <value>Celia</value>
        <documentation>Celia is a Finnish state-owned special library which produces and provides literature in accessible formats.</documentation>
            
        <value>Dedicon</value>
        <documentation>(...)</documentation>
        
        (...)
    </documentation>
    <documentation xmlns="http://relaxng.org/ns/compatibility/annotations/1.0" xml:lang="no">
        <value>Celia</value>
        <documentation>Celia er et statlig finsk spesialbibliotek som produserer litteratur i tilgjengelige formater.</documentation>
        
        (...)
    </documentation>
</choice>
```

...or maybe even this?

```xml
<choice id="dtbook-to-pef:braille-translator">
    
    <value>celia</value>
    <documentation xmlns="http://relaxng.org/ns/compatibility/annotations/1.0" xml:lang="en">
        <name>Celia</name>
        <description>Celia is a Finnish state-owned special library which produces and provides literature in accessible formats.</description>
    </documentation>
    <documentation xmlns="http://relaxng.org/ns/compatibility/annotations/1.0" xml:lang="no">
        <name>Celia</name>
        <description>Celia er et statlig finsk spesialbibliotek som produserer litteratur i tilgjengelige formater.</description>
    </documentation>
    
    <value>dedicon</value>
    <a:documentation>
        (...)
    </a:documentation>
    
    (...)
</choice>
```

(the support for multiple languages isn't something we'd really use in the web ui though; it's just for the example)

**Comment by bertfrees** [comment]
I like the second one!

**Comment by josteinaj** [comment]
Cool, let's do that then. For this sprint we'll keep it as it is without descriptions (if enums will be used at all for this sprint).

**Comment by bertfrees** [comment]
The second approach seems more established: see https://www.oasis-open.org/committees/relax-ng/compatibility.html#IDAC1YR:

> If an `a:documentation` element does not have a preceding sibling element from the RELAX NG namespace, then the specified documentation applies to the parent element. Otherwise, the specified documentation applies to the nearest preceding sibling element from the RELAX NG namespace. There may be multiple `a:documentation` elements specifying documentation that apply to the same RELAX NG element.

However the paragraph below that says that the `a:documentation` should not have any child elements. So maybe instead of `name` and `description` do first line vs. next lines?

```xml
<documentation xmlns="http://relaxng.org/ns/compatibility/annotations/1.0">Celia
Celia er et statlig finsk spesialbibliotek som produserer litteratur i tilgjengelige formater.</documentation>
```

**Comment by josteinaj** [comment]
For future reference: the Windows guidelines you linked in daisy/pipeline-webui#42 has this to say about rendering descriptions for radio buttons:

> If the option requires further explanation, provide the explanation in a static text control using complete sentences and ending punctuation.

Screen shot of radio buttons with explanatory text

> In this example, the options are explained using separate static text controls.

> **Note** Adding an explanation to one radio button doesn't mean that you have to provide explanations for all the radio buttons. Provide the relevant information in the label if you can, and use explanations only when necessary. Don't merely restate the label for consistency.

**Comment by josteinaj** [comment]
> However the paragraph below that says that the a:documentation should not have any child elements. So maybe instead of name and description do first line vs. next lines?

Ok. Yeah, that would work. And it would presumably be parsed as markdown the same way as for the script/template documentation. And since "If an a:documentation element does not have a preceding sibling element from the RELAX NG namespace, then the specified documentation applies to the parent element", we should probably drop multi-language support? So then this would be valid:

```xml
<choice id="dtbook-to-pef:braille-translator">
    
    <value>celia</value>
    <documentation xmlns="http://relaxng.org/ns/compatibility/annotations/1.0" xml:space="preserve">
        Celia
        
        [Celia](celia.fi) is a Finnish state-owned special library which produces and provides literature in accessible formats.
    </documentation>
    
    <value>dedicon</value>
    <documentation xmlns="http://relaxng.org/ns/compatibility/annotations/1.0" xml:space="preserve">Dedicon
Dedicon is a **Dutch** special library which produces and provides literature in accessible formats.</documentation>
    
    <value>mtm</value>
    <!-- no name/description, but it's ok. documentation belongs to first preceding sibling which must be a <value> -->
    
    <value>nlb</value>
    <documentation xmlns="http://relaxng.org/ns/compatibility/annotations/1.0" xml:space="preserve">NLB</documentation>
    <!-- nlb only has a name -->
    
    (...)
</choice>
```

**Comment by bertfrees** [comment]
Multi-language is supported alright. "Preceding sibling" does not mean "first preceding sibling".

**Comment by josteinaj** [comment]
Ah, I misinterpreted it. Yes you're right, multi-language will be supported.

**Comment by josteinaj** [comment]
@bertfrees I don't think there's any changes in this branch that we need. Should we close it? I'll crate new issues for moving the documentation elements closer to their values as well as supporting dynamic descriptions in the webui.

**Comment by bertfrees** [comment]
OK. I've been wanting to delete this branch.

**Pull request closed without merging**
