### PR TITLE
Release v1.10.0

### PR DESCRIPTION
**Pull request by rdeltour**

### CODE REVIEW

**Comment by bertfrees** [comment]
@rdeltour See https://github.com/daisy/pipeline-mod-braille/pull/140/commits/952214ee825cabc53a8ab2fdd616296780ee9df8. I always do this manually after a release (and then I amend it to the previous commit).

**Comment by rdeltour** [comment]
ok, will do it for the all the other PRs before merging then!

**Comment by bertfrees** [comment]
I've been doing it for the braille modules, but maybe there is a better, less manual way.

**Comment by rdeltour** [comment]
yeah, I always do it manually at pre-release time, but I agree that it's better done post-release. An automated option w/b helpful, but I don't think it's easily feasible with existing Maven plugins.

**Pull request closed without merging**
